name: Scan Repository

on:
  # 这里可以添加多个触发条件
  workflow_dispatch: # 允许手动触发

jobs:
  scan:
    runs-on: ubuntu-latest  # GitHub 提供的 Ubuntu 服务器

    steps:
      - name: Checkout Repository
        # GitHub Actions 提供的一个官方 Action，用于拉取代码，@4 表示是 v4 版本
        uses: actions/checkout@v4
        with:
          ref: master  # 只拉 master 分支
          token: ${{ secrets.GITHUB_TOKEN }} # 获取 Token，用于后续推送

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 选择 Python 版本

      - name: Run Scan Script
        run: python pack.py  # 运行 Python 脚本，这里直接使用 python 即可（不是 python3）

      # 生成一个用户可以下载的文件（临时）
      # 长期文件可以创建 Release
      - name: Upload Artifact (File)
        uses: actions/upload-artifact@v4
        with:
          name: pack-result # 压缩文件名
          path: pack_result_leaset.txt  # 你想让用户下载的文件
          retention-days: 3 # 临时文件不要占用太多公共资源

      # 这种写法需要确保在 push 之前，没有新的 commit 产生
      # 因为 clone depth 为 1，而且没有处理冲突
      # 另外 如果 commit 失败了就 echo 信息
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pack_log_leaset.txt
          git commit -m "Automated scan results update: pack_log_leaset.txt" || echo "No changes to commit"
          git push origin master